### ISSUE TITLE
as an admin, I would like to create a batch of task participants and accounts if needed

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#1054]
We need to do this for historical task participants.  (In the future I can imagine cases where we might want to auto-create a set of accounts for other reasons)

Suggested interface:  paste in data or upload a csv and add participants (without sending them a welcome email)

Steps:
1.  check for user
2.  create user
3. add agency tag

Ideally, we would then display a confirmation page with all the user names and links to their profiles (whether or not they are new)

**Comment by ultrasaurus** [comment]
Let's make a one time import script:
name, email, agency, task_id

**Comment by ultrasaurus** [comment]
proposed format here:  https://docs.google.com/spreadsheets/d/1ozvIM5hX0239ErYz6_aOHnQNuaWq7L4s-lgM9PIN018/edit#gid=1928879704

**Comment by dhcole** [comment]
To keep this limited to running an import of a spreadsheet, we'd need the following information.

The tasks should already be in the database, so the only thing we want for a task is its ID. Task name, state, and completion time would be ignored.

For participant, we should have name and email. If an email exists in the databased, we'll use that user record. If it doesn't, we'd have to create a new user record for that address using the email address and user name.

Entering agency information would be a manual process of finding the users and editing their profile, and adding their agencies.

I see two main issues with this approach: 1) we'll be involuntarily signing up a bunch of people for accounts. They'll either need to get password reset emails to log in or, we don't send any email, and they have no idea they have an account until they try to sign up and are blocked (because they already have an account; 2) we don't have any automated way to try to guess agency from email, which is why I'm saying setting a user's agency would be a manual follow up.

**Comment by ultrasaurus** [comment]
@dhcole these folks are already Open Opportunities users, just not users of the new platform... I think we can set expectations with a follow-up email.

It would be convenient to import agencies, rather than manually entering them.  Will it work if we use the exact same ageny name that is already in Open Opps and put that in another column?  (We have a UI for adding agencies, if needed)

**Comment by dhcole** [comment]
Since agencies are tags, not part of the user model, we'd need to add more steps to the process to match them on names. Right now it would be:

1. findOrCreate users
2. create volunteer records (associate userId with a taskId)

We'd need to add: 

3. findOrCreate agency tags
4. associate agency tags with users

So it would save time during upload but lead to additional development work. Maybe an extra 1/2 day to develop and test. Not sure if that outweighs the manual time it would take; that depends on how many participant records we're actually importing.

**Comment by ultrasaurus** [comment]
@dhcole after sleeping on this, lets just punt on the agency tag thing... many of the users will already be in the system.  With the confirmation page that I suggested in the description, should be quick enough to add manually.

**Comment by dhcole** [comment]
It would be simpler to do this as a direct import to the database though, which would bypass notifications. Are you opposed to that approach? This is really a one-time case for migrating from a legacy system.

**Comment by ultrasaurus** [comment]
this got done the week before last -- closing!
