### ISSUE TITLE
As a task creator, I should be able to better specify when it should be completed

### ISSUE THREAD

**Issue by gwynnek** [18F/midas#290]
On the Create Opportunity screen, in addition to the "day, days, week, month, few month," add an option with a specific due date.

**Comment by ultrasaurus** [comment]
We need to support:  https://github.com/18F/midas-open-opportunities/issues/35
For specific dates (like April 4, 2015) the workaround of putting text in the description is fine

**Comment by dhcole** [comment]
@ultrasaurus do you have a final list / mock-up of the selection options that should be present? Seems like the lists here and in 18F/midas-open-opportunities#35 are a bit old so I want to make sure I have the latest.

**Comment by ultrasaurus** [comment]
Here's a design which can accomodate the Open Opps time commitments (and I think improves the information architecture in general):
![image](https://cloud.githubusercontent.com/assets/41906/6337653/ff341290-bb5f-11e4-8f51-b0b457e1eb6b.png)

The idea is if someone switches the first popup to "Full-time"  (or 20% in Open Opps) then we would hide "will required [amount of time] of work, and"  since the amount of time is already specified in the first popup.

**Comment by ultrasaurus** [comment]
For open opps, Part-Time / Full-Time would be customized as:
* Quick
* On-going

And:
* a few minutes to 1 hour
* up to 2 hours
* 2-4 hours
* 4-8 hours
* 8-16 hours
* 16-24 hours
* 24-40 hours

must be complete within: [1 week, 1 month, 3 months, 6 months]

from the discussion here:  https://github.com/18F/midas-open-opportunities/issues/35

**Comment by dhcole** [comment]
@jeremiak summing up recent conversations, opportunities are defined by three types of tags, as listed above in @ultrasaurus's comment. To close out this task, we need to 

- [ ] change the existing tags from "part-time", "full-time", and "20%" to  `["one-time", "on-going"]`
- [ ] adjust the duration times to match the above comment
- [ ] adjust the completion time frames to match the above comment
- [ ] restructure the form to read like "This [one-time, on-going] task will require [duration] of work ["each week" if on-going], and must be completed within [completion time frame]

**Comment by jeremiak** [comment]
Quick question, will this require a migration? I just want to make sure I understand how tags work and it seems like the first three items on your comment @dhcole require a db migration. Am I correctly understanding how the tags work per the updated the wiki page?

**Comment by dhcole** [comment]
Not sure exactly. @ultrasaurus should we migrate these tags from the old ones to match the new ones in your comment above?

**Comment by jeremiak** [comment]
I guess the other alternative would be to just build a mapping into the Backbone application, but that seems like incurring more debt than this is worth?

**Comment by dhcole** [comment]
Nah, it should either be: 1) just leave the old tags and make new ones, or 2) rename all the old ones to match new values

**Comment by dhcole** [comment]
Choice depending on whether we need to map historical tags to current uses

**Comment by dhcole** [comment]
Which we may need to do since some tasks are still open... I'm thinking we probably need to do 2.

**Comment by jeremiak** [comment]
Agreed, so that makes me think migration. Cool, I'll put that in the branch for this issue as well.

**Comment by ultrasaurus** [comment]
Sorry, I must be missing something.  Why would migration be necessary?  We would just drop the "20%" from the full-time / part-time popup -- to my knowledge that has never been used, although we could migrate that to "part-time" if @brandtheisey thinks the migration script would be helpful for the State deployment.

**Comment by brandtheisey** [comment]
Assuming I understand the issue correctly, we are going to change the task-time-required tags in the default to something else along with changing some associated flavor text to make the new values fit better. If that's the case it's just data change it's a no different than how I have a bunch of State tags loaded and you guys don't. You can change or delete them, AFAIK without affecting me. 

You can even make a tool script to do the delete and insert if you need to and that way it can be optional.

That being said, I think I like the new tags betters and text better, but it's not clear to me what the State audience will think.

**Comment by jeremiak** [comment]
Ok, good to know that the tags are loaded differently into each instance of the platform. That being said, we load the default tags into the database with `npm run init`. I've gone ahead and changed that in #872 but how do we want to handle having these new tags show up on the open opportunity instance? To revisit the topic from above in the thread, I think we need a migration because there are `tagentities` in production that will be using the old tags and the front end application knows nothing about what the tags mean. It simply asks for tags of a certain type and then iterates through those.

**Comment by jeremiak** [comment]
The last bit for us to confirm before we merge #872 is to confirm that mappings that will take place for existing application instances. Right now I have the following:

```
var tagsToRename = {
    'Part Time': 'One time',
    'Full Time': 'On going',
    '1 Week': '1 week',
    '1 Month': '1 month',
    'A Few Months': '3 months',
    '1 - 3 hours': 'Up to 2 hours',
    '9 - 24 hours': '8 - 16 hours'
  };

  var newTagNamesToAdd = [
    { type: 'task-length', name: '6 months' },
    { type: 'task-time-estimate', name: '2 - 4 hours' },
    { type: 'task-time-estimate', name: '16 - 24 hours' },
    { type: 'task-time-estimate', name: '24 - 40 hours' }
  ];

  var tagNamesToMigrate = {
    '20% Time': 'On going',
    '1 Day': '1 week',
    '1 - 3 Days': '1 week',
    'longer than 40 hours': '24 - 40 hours'
  };
```

`tagsToRename` is a mapping of direct renaming. For example the name of one tag entity will change from `Part Time` to `'One time`.

`newTagNamesToAdd` are tags (with their name and type) that don't yet exist and will be added.

`tagNamesToMigrate` are tags where the associated records will be moved to the value (i.e. tasks tagged with `20% Time` will be tagged with `On going` instead), and then the old tag (`20% time`) will be deleted from the database so the task creation and editing UI stays clean and sane.

@ultrasaurus could you comment on if this mapping of tags makes sense and is a go? I will then update the migrate script on the feature branch.

**Comment by ultrasaurus** [comment]
This looks good for mapping.  It appears that "ongoing" is one word -- I thought it was hypenated but the [dictionary](http://dictionary.reference.com/browse/ongoing) and the [internet](http://www.future-perfect.co.uk/grammar-tip/is-it-on-going-or-ongoing/) tell me otherwise.

Also, did we decide against title caps?

**Comment by jeremiak** [comment]
@ultrasaurus I just took the copy right out of the above issue thread but I don't have a strong opinion either way.

**Comment by ultrasaurus** [comment]
Would be good for @GailSwanson to weigh in.  I didn't mean to change capitalization policy when I wrote the words in the list above :)

**Comment by GailSwanson** [comment]
It would make sense to use the most common capitalization schemes. 
Titlecase for titles, headlines, and headings
Initial caps for bullets and lists (no punctuation at the end of bullets)

**Comment by jeremiak** [comment]
@GailSwanson so these "tags" appear in a few different UI places but here is one of them (from above)
![](https://cloud.githubusercontent.com/assets/41906/6337653/ff341290-bb5f-11e4-8f51-b0b457e1eb6b.png). Since these are lists in this UI I'm going to stick with initial caps.

@ultrasaurus Changing "On going" to "Ongoing"

**Comment by jeremiak** [comment]
#872 got merged, so closing this issue.
