### ISSUE TITLE
"Sign up now" link should be more prominent

### ISSUE THREAD

**Issue by louh** [18F/midas#308]
Users at the 18F Hack Night reporting that the "Sign up now" link on the Login or Register dialog box is not that easy to find.

![screenshot 2014-10-06 18 03 04](https://cloud.githubusercontent.com/assets/2553268/4534353/b0b84dd0-4da4-11e4-92a3-9f47336e640c.png)

**Fun activity** How quickly can you find the "sign up now" link?

**Comment by lixonic** [comment]
![github-midas](https://cloud.githubusercontent.com/assets/934220/5603046/00f0ccd0-9398-11e4-8df5-bf6c8a9e508b.png)

**Comment by ultrasaurus** [comment]
That looks an easy quick fix that would make a big difference.  Want to give us a hex color you recommend?  or a pull request is welcome if you are an HTML/CSS kind of contributor!

Thanks for scrubbing in @lixonic !

**Comment by polastre** [comment]
What would be more noticeable is a big button on the left "Sign Up Now" and then the small text "Forgot your password?" under the "Sign In" button.  Just an idea.

There can be confusion that filling out your email and password on this form will carry over to the "Sign up now" form.  I'd advise that we copy that info over for someone if they do input it, because it is frustrating to have to enter it over and over.

**Comment by lixonic** [comment]
unless the 'sign up now' isn't a button, users can distinguish what's the call to action in that modalbox.  we all expect a button for signing in ,right? :)

**Comment by ultrasaurus** [comment]
yeah, right now it is a link, I think it is true that people expect a button

@lixonic: feel like experimenting with a mock that has a more button-like visual treatment?

**Comment by polastre** [comment]
@ultrasaurus I think @lixonic was proposing just the opposite:

> we all expect a button for signing in ,right? :)

If the sign up link is a button, then it could be confused with the sign in button.

**Comment by lixonic** [comment]
@polastre exactly . thoughts?

**Comment by dhcole** [comment]
Resolved in #516
