### ISSUE TITLE
I should not be required to be logged in to see profiles

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#466]
As we start thinking about a way to "browse" people, I think the profiles should be public.  State has the whole thing behind a firewall, but for most use cases, I think public info will streamline collaboration.

**Comment by polastre** [comment]
@ultrasaurus I'm not convinced of this.  Most sites put profiles behind a firewall to ensure a small amount of privacy.  I wouldn't be comfortable with filling out my profile if I knew anyone in the public could view.  I would prefer that only my federal coworkers can view it.

Since Open Opportunities is a public website, I would be hesitant to put all my details in my profile.  For example, for collaboration within GSA, I'd be willing to put my phone number and contact details in my bio.  But I wouldn't put that in a site that I knew the public could index (Google) and access.  Even LinkedIn provides user controls that limit what information can be seen by people not logged in.

**Comment by dhcole** [comment]
@ultrasaurus what's your latest thinking on this?

**Comment by dhcole** [comment]
Doesn't seem to be any movement on this so I'm closing. Let's re-open if this becomes actionable.
