### ISSUE TITLE
As a new member, I should be prompted to fill out my profile after I sign up

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#700]
Next step after signing up.  Show another dialog, with
* agency (required)
* location (required)
* A brief public biography (optional) with large text area (like in profile)

[Go to My Profile] [Browse Tasks]

related:
https://github.com/18F/midas/issues/464 Prompt people to fill out their profile, if they haven't already, when they add a task or project
https://github.com/18F/midas/issues/463 Prompt people to fill out their profile, if they haven't already, when they volunteer

**Comment by dhcole** [comment]
Per sprint-planning conversation, we discussed refactoring the sign-up process into this:

![img_5137](https://cloud.githubusercontent.com/assets/170641/8167687/eb8b973e-136d-11e5-8af3-be462b47680c.JPG)

This would kick in at any point a user tries to create a new account. It's a series of modal screens where the account is not actually created until the user makes it through both steps. Users can start with email and password or oauth, but they both then need to be validated as having a federal email address.

Name, email, password, and agency are required fields.

@brandtheisey how will this affect your environment? I'm thinking since all of your users are automatically signed in, they would bypass this whole process.

@jeremiak I'll work on the API-level components of this, like verifying an email is on the federal domain list and returning a matching agency name for a given email domain. The rest of the work should all take place at the backbone level.

**Comment by dhcole** [comment]
@ultrasaurus please verify my memory here on the flow when you have a moment.

**Comment by ultrasaurus** [comment]
Looks right to me, except we talked about an optional text area for bio. Th

**Comment by dhcole** [comment]
Thanks, I forgot that.

**Comment by jeremiak** [comment]
Just an update on this issue before the weekend, working off of the `agency-location-signup` branch.

I have added an agency and location config options to `login.json` and when either are present the registration form becomes two forms. The first sub-view is identical to the current view, except instead of 'Submit' the positive button says 'Next'. This is because there is a secondary sub-view that contains the registration options that are configured on.

The registration works fine and there is client side validation that all the present forms are properly filled out. However, the API doesn't accept the extra parameters of location and agency, which are `TagEntity` IDs. Will work on that next and then making sure to update/expand the tests.
