### ISSUE TITLE
As an admin, I would like to see agency and location in user.csv file

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#717]
current user.csv includes:
* user_id
* name
* username (email)
* title
* bio
* isAdmin
* disabled

related to:  https://github.com/18F/midas/pull/691

**Comment by sefk** [comment]
I was going to take a look at this @ultrasaurus but I'd rather not until @dhcole's new tagging branch lands. Adding some dumb subqueries that will just have to be replaced with proper joins isn't smart.

**Comment by dhcole** [comment]
Thanks @sefk. Tags work will be merged tomorrow. Also @csarsam already started on this task in #733 so I think we're all set here.

**Comment by sefk** [comment]
I was so excited to try out your new branch @dhcole I went ahead and added these columns just now without noticing your comment or that @csarsam had done some work here too. I'll go ahead and submit my PR, since it's done, and you can decide which branch to pull.

Note highlighting in this screenshot is just to draw attention to new columns, that's not how the report actually exports. :)

![userexp-agency-location](https://cloud.githubusercontent.com/assets/621565/7357457/c4e90072-ece3-11e4-91ac-1ab540af3156.png)

**Comment by ultrasaurus** [comment]
resolved with https://github.com/18F/midas/pull/733
