### ISSUE TITLE
Replace the word volunteered on individual profile pages

### ISSUE THREAD

**Issue by LisaLNelson** [18F/midas#822]
I suggest replacing the word volunteered with "Opportunities Signed Up For".

![image](https://cloud.githubusercontent.com/assets/9039852/7946312/f56f9946-0943-11e5-9168-11bdd9212b22.png)

**Comment by ultrasaurus** [comment]
We also want to address these issues:
* https://github.com/18F/midas-open-opportunities/issues/58
* https://github.com/18F/midas-open-opportunities/issues/82

**Comment by ultrasaurus** [comment]
I think the original description was inacurate -- it said "Opportunities Completed" but that section has open & closed, so I changed it to "Opportunities Signed Up For"

**Comment by dhcole** [comment]
@jeremiak not sure if this and the two above have been addressed. In general "volunteer" is an inaccurate way to describe participation that has unintended implications. Uses participate instead of volunteer using this platform. We want replace all public-facing references to volunteer with participate. Variables and code-only occurrences are fine.

**Comment by jeremiak** [comment]
Note to self on copy changes like this. Don't do it in the templates! Use the translation strings in `/locales`

**Comment by dhcole** [comment]
Closed by #852
