### ISSUE TITLE
Discussion: improve perf/scale by serving profile pictures directly from storage

### ISSUE THREAD

**Issue by sefk** [18F/midas#915]
I noticed on the [midas dev server](https://midas-dev.18f.us/) that my profile image takes a loooong time to load. The page is viewable in 1.3s, but the image takes another 1.6 sec to download after then. 

<img width="816" alt="midas-homepage-waterfall" src="https://cloud.githubusercontent.com/assets/621565/8764990/06140948-2dad-11e5-9497-7211cb87b4b3.png">

I believe my pic is representative: 679kB, 718px square, png. 

Can we serve those static images directly from where they're stored, presumably S3? Lots of benefits:

- faster
- offload the serve time / connection maintenance from our app servers
- easy on-ramp to a CDN

Of course there may be other reasons why serving from /api makes sense. Seems like a worthwhile discussion to start.

**Comment by dhcole** [comment]
@sefk we recently moved all uploaded files to S3. We still proxy the files through the app though, so we can set access controls with Sails policies. Until recently, we still had the data for files still in the database as a `blob`, we've since dropped that. I'm seeing better response times. Still room for improvement, especially realized by serving assets directly from S3, but it seems pretty reasonable now. Are you still seeing a lot of lag?

<img width="887" alt="screen shot 2015-08-10 at 4 26 48 pm" src="https://cloud.githubusercontent.com/assets/170641/9183448/20b603aa-3f7d-11e5-9e05-dd506198b6df.png">

**Comment by sefk** [comment]
Still seems pretty slow to me, sorry to say @dhcole. Against the [dev server](https://midas-dev.18f.us/projects) my waterfall chart shows almost 4 sec for that page, with 2.3 sec being my pic. Which isn't that big. Screenshot below.

In terms of the site performance the really troubling thing isn't that image, but the nearly 0.9 sec to get the js. That's what would really drive interactive performance.

I'm fine if you want to close/ignore this because it's something about the dev server. I'm not pushing on this, just telling you what I'm seeing (still).

![screen shot 2015-08-11 at 9 36 30 am](https://cloud.githubusercontent.com/assets/621565/9203545/ad71f256-400c-11e5-90a6-c873d24942bf.png)

**Comment by dhcole** [comment]
Thanks for sharing this @sefk. I appreciate the report. I agree 4s for this page is way too long the the delay for the JS file is a problem. I don't know why your image is taking to so long. Here's what I see on the same page, which is much more reasonable.

<img width="1080" alt="screen shot 2015-08-12 at 12 04 30 pm" src="https://cloud.githubusercontent.com/assets/170641/9229279/50f6709a-40ea-11e5-99a5-fbbc83310260.png">

When I view your profile page, I get your image much faster too:

<img width="762" alt="screen shot 2015-08-12 at 12 08 09 pm" src="https://cloud.githubusercontent.com/assets/170641/9229380/dd3a583c-40ea-11e5-8e48-7205d7ae669d.png">

Again, not super fast, but much more reasonable.

So that has me thinking it may be geographic. Perhaps because all of our AWS resources are based in the east region, you're seeing more latency.

There are definitely things we can do at the software level to help here, like better resizing of images after upload and directly serving uploaded files from S3 instead of proxying though node.js, but the majority of things that would help seem like infrastructure tasks.

We could set up another region in AWS, but given our users are mostly DC-based, that doesn't seem worth the cost and complexity of load-balancing across regions. 

A CDN would help with a lot of that. We could immediately cache all static assets. We could make changes to the html templates to make them more cacheable, for instance, by passing error messages over query strings or cookies instead of inserting them dynamically into the templates. 

To cache the API better, we'd need to bust the cache on requests after update actions take place, like after adding a new task. That seems the most complex but would really help with issues like scaling the task listing page (given how overly complex the Sails / waterline association query is on that page).

Again thanks for helping me think through this. Since it seems like we not be affected as much in the DC area, I don' think this is an immediate priority, but there are some things to consider here as we make upgrades to the hosting infrastructure.
