### ISSUE TITLE
admin task dashboard is blank

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#928]
This is true on openopps-staging and midas-dev
![image](https://cloud.githubusercontent.com/assets/41906/9010370/58d4a50e-375b-11e5-9a54-3053357bfba0.png)

**Comment by dhcole** [comment]
This was just a case of a user with a task being deleted from the system. Duplicate users were removed. In production, we made sure none of the deleted users has associated tasks, but we didn't check this for the staging or dev databases. Fixed by either deleting the errant test data or by assigning it to an arbitrary user.
